name: codacy-coverage-reporter

on:
  push:
    branches:
      - main
jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - run: npm run coverage
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}